p

diff --git a/0x05-processes_and_signals/100-process_and_pid_file b/0x05-processes_and_signals/100-process_and_pid_file
--- a/0x05-processes_and_signals/100-process_and_pid_file
+++ b/0x05-processes_and_signals/100-process_and_pid_file
@@ -1,30 +1,29 @@
 #!/usr/bin/env bash
-# This script will:
-# Creates the file /var/run/holbertonscript.pid containing its PID
-# Displays To infinity and beyond indefinitely
-# Displays I hate the kill command when receiving a SIGTERM signal
-# Displays Y U no love me?! when receiving a SIGINT signal
-# Deletes the file /var/run/holbertonscript.pid and terminates itself when receiving a SIGQUIT or SIGTERM signal
 
+# Function to handle signals and clean up before exiting
+cleanup() {
+    echo "Cleaning up and terminating"
+    rm /var/run/holbertonscript.pid
+    exit
+}
+
+# Trap SIGQUIT and SIGTERM signals and call the cleanup function
+trap cleanup SIGQUIT SIGTERM
+
+# Function to handle SIGINT signal
+ctrl_c() {
+    echo "Y U no love me?!"
+}
+
+# Trap SIGINT signal and call ctrl_c function
 trap ctrl_c INT
-trap kill_process SIGTERM SIGQUIT
 
-function kill_process()
-{
-	echo "I hate the kill command"
-	sudo rm /var/run/holbertonscript.pid
-	sudo kill -SIGKILL $$
-}
+# Create PID file
+echo $$ > /var/run/holbertonscript.pid
 
-function ctrl_c()
-{
-	echo "Y U no love me?!"
-}
-
-sudo sh -c 'echo $$ >> /var/run/holbertonscript.pid'
-
-while true
-do
+# Infinite loop
+while true; do
     echo "To infinity and beyond"
     sleep 2
 done
+
